services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ft_transcendence_frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - frontend_data:/app/public
    networks:
      - ft_transcendence_network
    depends_on:
      - backend

networks:
  ft_transcendence_network:
    driver: bridge

volumes:
  frontend_data:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/frontend
      o: bind
