services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ft_transcendence_frontend
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - frontend_data:/app/public

volumes:
  frontend_data:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/frontend
      o: bind
