services:
  nginx:
    image: nginx:alpine
    container_name: ft_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - ./backend/uploads:/uploads:ro          # host ./uploads → /uploads in nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ft_transcendence_backend
    restart: unless-stopped
    ports:
      - "3000"
      # - "3000:3000"
      # - "3443:3443" # HTTPS port
    volumes:
      - backend_data:/app/db
      - ./certs:/app/certs
      - ./.env:/app/.env
    environment:
      - NODE_ENV=production
    env_file:
      - ./.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ft_transcendence_frontend
    restart: unless-stopped
    ports:
      - "8080"
      # - "8080:8080"
      # - "8443:8443" # HTTPS port
    volumes:
      - frontend_data:/app/public
      - ./certs:/app/certs
      - ./.env:/app/.env
    env_file:
      - ./.env
    depends_on:
      - backend

volumes:
  frontend_data:
    driver: local
  backend_data:
    driver: local