export const translations: Record<Language, Record<string, string>> = {
    english: {
        language: "Language",
        settings: "Settings",
        dashboard: "Dashboard",
        profile: "Profile",
        chat: "Chat",
        friends: "Friends",
        game: "Game",
        tournament: "Tournament",
        logout: "Logout",
        customizeExperience: "Customize your experience and manage account settings",
        gamePreferences: "Game Preferences",
        securityPrivacy: "Security & Privacy",
        visualSettings: "Visual Settings",
        boardColor: "Board Color",
        paddleColor: "Paddle Color",
        ballColor: "Ball Color",
        scoreColor: "Score Color",
        powerUp: "Power-Up",
        preview: "Preview",
        saveGameSettings: "Save Game Settings",
        emailAddress: "Email Address",
        email: "Email",
        emailDescription: "Your email is used for important account notifications and security features",
        updateEmail: "Update Email",
        password: "Password",
        currentPassword: "Current Password",
        newPassword: "New Password",
        confirmNewPassword: "Confirm New Password",
        passwordHint: "Use at least 8 characters",
        changePassword: "Change Password",
        chooseLanguage: "Choose a language:",
        confirmation: "Confirmation",
        confirmMessage: "Are you sure you want to proceed?",
        cancel: "Cancel",
        confirm: "Confirm",
        english: "English",
        spanish: "Spanish",
        german: "German",
        createPlayTournament: "Create and play a tournament!",
        createTournament: "Create a tournament. Choose how many players you want to participate.",
        fourPlayers: "4 players",
        eightPlayers: "8 players",
        bioEmpty: "No bio yet",
        memberSince: "Member since:",
        noEmail: "No email provided",
        edit: "Edit Profile",
        addFriend: "Add Friend",
        rank: "Rank",
        level: "Level",
        games: "Games",
        winrate: "Win Rate",
        achievements: "Achievements",
        completedOn: "Completed on",
        noAchievements: "No achievements yet",
        matchHistory: "Match History",
        noMatches: "No matches played yet",
        loadMore: "Load More Matches",
        matchWon: "Won against",
        matchLost: "Lost against",
        playAgainstAI: "Play Against AI",
        multiplayer: "Multiplayer",
        selectPlayers: "Select number of players:",
        twoPlayers: "2 Players",
        welcomeBack: "Welcome back, ",
        lastLogin: "Last login: ",
        wins: "Wins",
        losses: "Losses",
        gameStatistics: "Game Statistics",
        gameResults: "Game Results",
        winRate: "Win Rate",
        basedOn: "Based on games played",
        noActivity: "No matches played yet",
        performanceOverview: "Performance Overview",
        totalGames: "Total Games",
        recentActivity: "Recent Activity",
        won: "Won",
        lost: "Lost",
        viewAllActivity: "View all activity",
        topPlayers: "Top Players",
        byWins: "By Wins",
        byWinrate: "By Win Rate",
        loadingLeaderboard: "Loading leaderboard...",
        connectWithPlayers: "Connect with other players and manage your friend list",
        searchForUsers: "Search for users...",
        search: "Search",
        myFriends: "My Friends",
        friendRequests: "Friend Requests",
        loadingFriends: "Loading friends...",
        incomingFriendRequests: "Incoming Friend Requests",
        loadingRequests: "Loading requests...",
        searchResults: "Search Results",
        searchForAddFriends: "Search for users to add them as friends",
        userName: "User Name",
        bio: "No bio yet",
        achievementName: "Achievement Name",
        achievementDesc: "Achievement Description",
        gameResult: "Won/Lost",
        loadMoreMatches: "Load More Matches",
        chatDescription: "Chat with your friends and other players",
        filterContacts: "Filter contacts...",
        loadingConversations: "Loading conversations...",
        welcomeToChat: "Welcome to Chat",
        selectContact: "Select a contact to start chatting.",
        typeMessage: "Type a message...",
        sendMessage: "Send",
        emailText: "No email provided",
        noContacts: "No contacts",
        noFriends: "You don't have any friends yet. Use the search to find other players.",
        leftPlayer: " Left Player",
        rightPlayer: " Right Player",
        displayName: "Display Name",
        editProfile: "Edit Profile",
        saveChanges: "Submit Changes",
        noFriendRequest: "You don't have any friend requests",
        noMessage: "No messages yet. Start a conversation!",
        noMessageYet: "No messages yet",
        inviteToGame: "Invite to Game",
        blockUser: "Block User",
    },
    spanish: {
        language: "Idioma",
        settings: "Configuraciones",
        dashboard: "Tablero",
        profile: "Perfil",
        chat: "Chat",
        friends: "Amigos",
        game: "Juego",
        tournament: "Torneo",
        logout: "Cerrar sesión",
        customizeExperience: "Personaliza tu experiencia y gestiona la configuración de la cuenta",
        gamePreferences: "Preferencias de Juego",
        securityPrivacy: "Seguridad y Privacidad",
        visualSettings: "Configuraciones Visuales",
        boardColor: "Color de Tablero",
        paddleColor: "Color de Paleta",
        ballColor: "Color de Pelota",
        scoreColor: "Color de Puntaje",
        powerUp: "Power-Up",
        preview: "Vista Previa",
        saveGameSettings: "Guardar Configuración de Juego",
        emailAddress: "Dirección de Correo Electrónico",
        email: "Correo Electrónico",
        emailDescription: "Tu correo electrónico se utiliza para notificaciones importantes y funciones de seguridad de la cuenta",
        updateEmail: "Actualizar Correo Electrónico",
        password: "Contraseña",
        currentPassword: "Contraseña Actual",
        newPassword: "Nueva Contraseña",
        confirmNewPassword: "Confirmar Nueva Contraseña",
        passwordHint: "Usa al menos 8 caracteres",
        changePassword: "Cambiar Contraseña",
        chooseLanguage: "Elige un idioma:",
        confirmation: "Confirmación",
        confirmMessage: "¿Estás seguro de que deseas continuar?",
        cancel: "Cancelar",
        confirm: "Confirmar",
        english: "Inglés",
        spanish: "Español",
        german: "Alemán",
        createPlayTournament: "¡Crea y juega un torneo!",
        createTournament: "Crea un torneo. Elige cuántos jugadores quieres que participen.",
        fourPlayers: "4 jugadores",
        eightPlayers: "8 jugadores",
        bioEmpty: "Aún no hay biografía",
        memberSince: "Miembro desde:",
        noEmail: "No se proporcionó correo electrónico",
        edit: "Editar Perfil",
        addFriend: "Añadir Amigo",
        rank: "Rango",
        level: "Nivel",
        games: "Juegos",
        winrate: "Tasa de Victorias",
        achievements: "Logros",
        completedOn: "Completado el",
        noAchievements: "No hay logros aún",
        matchHistory: "Historial de Partidas",
        noMatches: "No se han jugado partidas aún",
        loadMore: "Cargar más partidas",
        matchWon: "Ganó contra",
        matchLost: "Perdió contra",
        playAgainstAI: "Jugar Contra IA",
        multiplayer: "Multijugador",
        selectPlayers: "Selecciona el número de jugadores:",
        twoPlayers: "2 Jugadores",
        welcomeBack: "¡Bienvenido de nuevo, ",
        lastLogin: "Último inicio de sesión: ",
        wins: "Victorias",
        losses: "Derrotas",
        gameStatistics: "Estadísticas del juego",
        gameResults: "Resultados del juego",
        winRate: "Tasa de victorias",
        basedOn: "Basado en juegos jugados",
        noActivity: "Aún no se han jugado partidas",
        performanceOverview: "Resumen de rendimiento",
        totalGames: "Juegos totales",
        recentActivity: "Actividad reciente",
        won: "Ganado",
        lost: "Perdido",
        viewAllActivity: "Ver toda la actividad",
        topPlayers: "Mejores jugadores",
        byWins: "Por victorias",
        byWinrate: "Por tasa de victorias",
        loadingLeaderboard: "Cargando el clasificador...",
        connectWithPlayers: "Conéctate con otros jugadores y administra tu lista de amigos",
        searchForUsers: "Buscar usuarios...",
        search: "Buscar",
        myFriends: "Mis Amigos",
        friendRequests: "Solicitudes de Amistad",
        loadingFriends: "Cargando amigos...",
        incomingFriendRequests: "Solicitudes de amistad entrantes",
        loadingRequests: "Cargando solicitudes...",
        searchResults: "Resultados de Búsqueda",
        searchForAddFriends: "Busca usuarios para agregarlos como amigos",
        userName: "Nombre de usuario",
        bio: "Aún no hay biografía",
        editProfile: "Editar perfil",
        achievementName: "Nombre del logro",
        achievementDesc: "Descripción del logro",
        gameResult: "Ganado/Perdido",
        loadMoreMatches: "Cargar más partidos",
        chatDescription: "Chatea con tus amigos y otros jugadores",
        filterContacts: "Filtrar contactos...",
        loadingConversations: "Cargando conversaciones...",
        welcomeToChat: "Bienvenido al Chat",
        selectContact: "Selecciona un contacto para comenzar a chatear.",
        typeMessage: "Escribe un mensaje...",
        sendMessage: "Enviar",
        emailText: "Correo electrónico no proporcionado",
        noContacts: "Sin contactos",
        noFriends: "Aún no tienes amigos. Usa la búsqueda para encontrar otros jugadores.",
        leftPlayer: " Jugador Izquierdo",
        rightPlayer: " Jugador Derecho",
        displayName: "Nombre para mostrar",
        saveChanges: "Guardar cambios",
        noFriendRequest: "No tienes solicitudes de amistad",
        noMessage: "¡Aún no hay mensajes. ¡Inicia una conversación!",
        noMessageYet: "Aún no hay mensajes",
        inviteToGame: "Invitar a Juego",
        blockUser: "Bloquear usuario",
    },
    german: {
        language: "Sprache",
        settings: "Einstellungen",
        dashboard: "Übersicht",
        profile: "Profil",
        chat: "Chat",
        friends: "Freunde",
        game: "Spiel",
        tournament: "Turnier",
        logout: "Abmelden",
        customizeExperience: "Passen Sie Ihr Erlebnis an und verwalten Sie Kontoeinstellungen",
        gamePreferences: "Spielpräferenzen",
        securityPrivacy: "Sicherheit & Datenschutz",
        visualSettings: "Visuelle Einstellungen",
        boardColor: "Farbe des Spielfelds",
        paddleColor: "Farbe des Schlägers",
        ballColor: "Farbe des Balls",
        scoreColor: "Farbe des Scores",
        powerUp: "Power-Up",
        preview: "Vorschau",
        saveGameSettings: "Spiel Einstellungen speichern",
        emailAddress: "E-Mail Adresse",
        email: "E-Mail",
        emailDescription: "Ihre E-Mail wird für wichtige Kontobenachrichtigungen und Sicherheitsfunktionen verwendet",
        updateEmail: "E-Mail aktualisieren",
        password: "Passwort",
        currentPassword: "Aktuelles Passwort",
        newPassword: "Neues Passwort",
        confirmNewPassword: "Neues Passwort bestätigen",
        passwordHint: "Verwenden Sie mindestens 8 Zeichen",
        changePassword: "Passwort ändern",
        chooseLanguage: "Wählen Sie eine Sprache:",
        confirmation: "Bestätigung",
        confirmMessage: "Sind Sie sicher, dass Sie fortfahren möchten?",
        cancel: "Abbrechen",
        confirm: "Bestätigen",
        english: "Englisch",
        spanish: "Spanisch",
        german: "Deutsch",
        createPlayTournament: "Erstellen und spielen Sie ein Turnier!",
        createTournament: "Erstelle ein Turnier. Wähle, wie viele Spieler teilnehmen sollen.",
        fourPlayers: "4 Spieler",
        eightPlayers: "8 Spieler",
        bioEmpty: "Noch keine Biografie",
        memberSince: "Mitglied seit:",
        noEmail: "Kein E-Mail angegeben",
        edit: "Profil bearbeiten",
        addFriend: "Freund hinzufügen",
        rank: "Rang",
        level: "Stufe",
        games: "Spiele",
        winrate: "Gewinnrate",
        achievements: "Erfolge",
        completedOn: "Abgeschlossen am",
        noAchievements: "Noch keine Erfolge",
        matchHistory: "Spieleverlauf",
        noMatches: "Noch keine Spiele gespielt",
        loadMore: "Mehr Spiele laden",
        matchWon: "Gewonnen gegen",
        matchLost: "Verloren gegen",
        playAgainstAI: "Gegen AI spielen",
        multiplayer: "Mehrspieler",
        selectPlayers: "Wählen Sie die Anzahl der Spieler:",
        twoPlayers: "2 Spieler",
        welcomeBack: "Willkommen zurück, ",
        lastLogin: "Letzte Anmeldung: ",
        wins: "Siege",
        losses: "Niederlagen",
        gameStatistics: "Spielstatistiken",
        gameResults: "Spielergebnisse",
        winRate: "Siegesquote",
        basedOn: "Basierend auf gespielten Spielen",
        noActivity: "Noch keine Spiele gespielt",
        performanceOverview: "Leistungsübersicht",
        totalGames: "Gesamtspiele",
        recentActivity: "Letzte Aktivitäten",
        won: "Gewonnen",
        lost: "Verloren",
        viewAllActivity: "Alle Aktivitäten anzeigen",
        topPlayers: "Top-Spieler",
        byWins: "Nach Siegen",
        byWinrate: "Nach Siegesquote",
        loadingLeaderboard: "Lade Bestenliste...",
        connectWithPlayers: "Verbinde dich mit anderen Spielern und verwalte deine Freundesliste",
        searchForUsers: "Benutzer suchen...",
        search: "Suchen",
        myFriends: "Meine Freunde",
        friendRequests: "Anfragen",
        loadingFriends: "Freunde werden geladen...",
        incomingFriendRequests: "Eingehende Freundschaftsanfragen",
        loadingRequests: "Anfragen werden geladen...",
        searchResults: "Suchergebnisse",
        searchForAddFriends: "Suche nach Benutzern, um sie als Freunde hinzuzufügen",
        userName: "Benutzername",
        bio: "Noch keine Biografie",
        editProfile: "Profil bearbeiten",
        achievementDesc: "Erfolgsbeschreibung",
        achievementName: "Name der Leistung",
        gameResult: "Gewonnen/Verloren",
        loadMoreMatches: "Weitere Spiele laden",
        chatDescription: "Chaten Sie mit Ihren Freunden und anderen Spielern",
        filterContacts: "Kontakte filtern...",
        loadingConversations: "Lade Gespräche...",
        welcomeToChat: "Willkommen im Chat",
        selectContact: "Wählen Sie einen Kontakt, um zu chatten.",
        typeMessage: "Nachricht eingeben...",
        sendMessage: "Senden",
        emailText: "Keine E-Mail-Adresse angegeben",
        noContacts: "Keine Kontakte",
        noFriends: "Du hast noch keine Freunde. Benutze die Suche, um andere Spieler zu finden.",
        leftPlayer: " Linker Spieler",
        rightPlayer: " Rechter Spieler",
        displayName: "Anzeigename",
        saveChanges: "Änderungen speichern",
        noFriendRequest: "Du hast keine Freundschaftsanfragen",
        noMessage: "Noch keine Nachrichten. Starte ein Gespräch!",
        noMessageYet: "Noch keine Nachrichten",
        inviteToGame: "Zum Spiel einladen",
        blockUser: "Benutzer blockieren",
    }
};


export type Language = "english" | "spanish" | "german";

// Applies translations to all elements with [data-i18n]
export function applyTranslations(language: Language, toEnglish?: boolean) {
    if (language === 'english' && !toEnglish) return;
    const elements = document.querySelectorAll<HTMLElement>("[data-i18n]");
    elements.forEach(el => {
        const key = el.dataset.i18n!;
        const translatedText = translations[language][key] || translations["english"][key] || key;

        // Update placeholder for input/textarea, otherwise set textContent
        if (el instanceof HTMLInputElement || el instanceof HTMLTextAreaElement)
            el.placeholder = translatedText;
        if (el.hasAttribute('title'))
            el.setAttribute('title', translatedText);
        else
            el.textContent = translatedText;
    });
}
