export const translations: Record<Language, Record<string, string>> = {
    english: {
        language: "Language",
        settings: "Settings",
        dashboard: "Dashboard",
        profile: "Profile",
        chat: "Chat",
        friends: "Friends",
        game: "Game",
        tournament: "Tournament",
        logout: "Logout",
        customizeExperience: "Customize your experience and manage account settings",
        gamePreferences: "Game Preferences",
        securityPrivacy: "Security & Privacy",
        visualSettings: "Visual Settings",
        boardColor: "Board Color",
        paddleColor: "Paddle Color",
        ballColor: "Ball Color",
        scoreColor: "Score Color",
        powerUp: "Power-Up",
        preview: "Preview",
        saveGameSettings: "Save Game Settings",
        emailAddress: "Email Address",
        email: "Email",
        emailDescription: "Your email is used for important account notifications and security features",
        updateEmail: "Update Email",
        password: "Password",
        currentPassword: "Current Password",
        newPassword: "New Password",
        confirmNewPassword: "Confirm New Password",
        passwordHint: "Use at least 8 characters",
        changePassword: "Change Password",
        chooseLanguage: "Choose a language:",
        confirmation: "Confirmation",
        confirmMessage: "Are you sure you want to proceed?",
        cancel: "Cancel",
        confirm: "Confirm",
        english: "English",
        spanish: "Spanish",
        german: "German",
        createPlayTournament: "Create and play a tournament!",
    },
    spanish: {
        language: "Idioma",
        settings: "Configuraciones",
        dashboard: "Tablero",
        profile: "Perfil",
        chat: "Chat",
        friends: "Amigos",
        game: "Juego",
        tournament: "Torneo",
        logout: "Cerrar sesión",
        customizeExperience: "Personaliza tu experiencia y gestiona la configuración de la cuenta",
        gamePreferences: "Preferencias de Juego",
        securityPrivacy: "Seguridad y Privacidad",
        visualSettings: "Configuraciones Visuales",
        boardColor: "Color de Tablero",
        paddleColor: "Color de Paleta",
        ballColor: "Color de Pelota",
        scoreColor: "Color de Puntaje",
        powerUp: "Power-Up",
        preview: "Vista Previa",
        saveGameSettings: "Guardar Configuración de Juego",
        emailAddress: "Dirección de Correo Electrónico",
        email: "Correo Electrónico",
        emailDescription: "Tu correo electrónico se utiliza para notificaciones importantes y funciones de seguridad de la cuenta",
        updateEmail: "Actualizar Correo Electrónico",
        password: "Contraseña",
        currentPassword: "Contraseña Actual",
        newPassword: "Nueva Contraseña",
        confirmNewPassword: "Confirmar Nueva Contraseña",
        passwordHint: "Usa al menos 8 caracteres",
        changePassword: "Cambiar Contraseña",
        chooseLanguage: "Elige un idioma:",
        confirmation: "Confirmación",
        confirmMessage: "¿Estás seguro de que deseas continuar?",
        cancel: "Cancelar",
        confirm: "Confirmar",
        english: "Inglés",
        spanish: "Español",
        german: "Alemán",
        createPlayTournament: "¡Crea y juega un torneo!",
        createTournament: "Crea un torneo. Elige cuántos jugadores quieres que participen.",
        fourPlayers: "4 jugadores",
        eightPlayers: "8 jugadores",
    },
    german: {
        language: "Sprache",
        settings: "Einstellungen",
        dashboard: "Übersicht",
        profile: "Profil",
        chat: "Chat",
        friends: "Freunde",
        game: "Spiel",
        tournament: "Turnier",
        logout: "Abmelden",
        customizeExperience: "Passen Sie Ihr Erlebnis an und verwalten Sie Kontoeinstellungen",
        gamePreferences: "Spielpräferenzen",
        securityPrivacy: "Sicherheit & Datenschutz",
        visualSettings: "Visuelle Einstellungen",
        boardColor: "Farbe des Spielfelds",
        paddleColor: "Farbe des Schlägers",
        ballColor: "Farbe des Balls",
        scoreColor: "Farbe des Scores",
        powerUp: "Power-Up",
        preview: "Vorschau",
        saveGameSettings: "Spiel Einstellungen speichern",
        emailAddress: "E-Mail Adresse",
        email: "E-Mail",
        emailDescription: "Ihre E-Mail wird für wichtige Kontobenachrichtigungen und Sicherheitsfunktionen verwendet",
        updateEmail: "E-Mail aktualisieren",
        password: "Passwort",
        currentPassword: "Aktuelles Passwort",
        newPassword: "Neues Passwort",
        confirmNewPassword: "Neues Passwort bestätigen",
        passwordHint: "Verwenden Sie mindestens 8 Zeichen",
        changePassword: "Passwort ändern",
        chooseLanguage: "Wählen Sie eine Sprache:",
        confirmation: "Bestätigung",
        confirmMessage: "Sind Sie sicher, dass Sie fortfahren möchten?",
        cancel: "Abbrechen",
        confirm: "Bestätigen",
        english: "Englisch",
        spanish: "Spanisch",
        german: "Deutsch",
        createPlayTournament: "Erstellen und spielen Sie ein Turnier!",
        createTournament: "Erstelle ein Turnier. Wähle, wie viele Spieler teilnehmen sollen.",
        fourPlayers: "4 Spieler",
        eightPlayers: "8 Spieler",
    }    
}

export type Language = "english" | "spanish" | "german";

// Type guard to ensure selected value is a valid Language
export function isLanguage(value: string): value is Language {    
    return ["english", "spanish", "german"].includes(value);
} 

// Applies translations to all elements with [data-i18n]
export function applyTranslations(language: Language) {
    const elements = document.querySelectorAll<HTMLElement>("[data-i18n]");
    elements.forEach(el => {
        const key = el.dataset.i18n!;
        const translatedText = translations[language][key] || translations["english"][key] || key;
        el.textContent = translatedText;
    });
}